// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

console.log("Hello, BuckleScript and Reason!");

var jsMapperConstantArray = [
  /* tuple */[
    -910341463,
    "white"
  ],
  /* tuple */[
    888264127,
    "black"
  ]
];

function staticColorToJs(param) {
  return Js_mapperRt.binarySearch(2, param, jsMapperConstantArray);
}

function staticColorFromJs(param) {
  return Js_mapperRt.revSearch(2, jsMapperConstantArray, param);
}

var jsMapperConstantArray$1 = [
  /* tuple */[
    284104899,
    "foreground"
  ],
  /* tuple */[
    639472622,
    "background"
  ]
];

function themeStyleColorToJs(param) {
  return Js_mapperRt.binarySearch(2, param, jsMapperConstantArray$1);
}

function themeStyleColorFromJs(param) {
  return Js_mapperRt.revSearch(2, jsMapperConstantArray$1, param);
}

function colorFromJs(str) {
  var maybeThemeStyleColor = themeStyleColorFromJs(str);
  var maybeStaticColor = staticColorFromJs(str);
  if (maybeThemeStyleColor !== undefined) {
    if (maybeStaticColor !== undefined) {
      return ;
    } else {
      return maybeThemeStyleColor;
    }
  } else if (maybeStaticColor !== undefined) {
    return maybeStaticColor;
  } else {
    return ;
  }
}

console.log(colorFromJs("white"));

exports.staticColorToJs = staticColorToJs;
exports.staticColorFromJs = staticColorFromJs;
exports.themeStyleColorToJs = themeStyleColorToJs;
exports.themeStyleColorFromJs = themeStyleColorFromJs;
exports.colorFromJs = colorFromJs;
/*  Not a pure module */
